### PR TITLE
handle overlapping deletions

### LINKED ISSUE #61: Add handling of overlapping deletion alleles ("*")
**Describe the issue**
I stumbled on an unaccounted for genotyping edge-case: the notation used to indicate an overlapping deletion in a genotype call.
More info here: https://gatk.broadinstitute.org/hc/en-us/articles/360035531912-Spanning-or-overlapping-deletions-allele
The asterisk `*` is used in VCF format to denote such an allele, and it is not a recognized allele format by the dosage calculator function `convert.alleles.to.pgs.dosage`.

**To Reproduce**
```
> convert.alleles.to.pgs.dosage('A/*', 'A')
Error in convert.alleles.to.pgs.dosage("A/*", "A") : 
  unrecognized called.alleles format, must be capitalized letters or "." separated by a slash or pipe.
```

**Expected behavior**
I think an appropriate way to handle an `*` allele in the context of allele dosage is to treat it like a non-risk allele and assign a dosage of 0.

### PR DESCRIPTION
**Pull request by alkaZeltser**
#61 Outlines a bug: the notation used to indicate an overlapping deletion in a genotype call is not recognized by `convert.alleles.to.pgs.dosage`.

More info here: https://gatk.broadinstitute.org/hc/en-us/articles/360035531912-Spanning-or-overlapping-deletions-allele

The asterisk `*` is used in VCF format to denote such an allele, and it is not a recognized allele format by the dosage calculator function `convert.alleles.to.pgs.dosage`.

I have decided to add `*` to the allowed list of sample alleles but not to the list of allowed risk alleles. This means that an `*` will always be treated as non-risk and will contribute a dosage of 0.

@RoniHaas would you mind weighing in on whether you've encountered this notation in your research and how you think they should be handled?

- Updated `convert.alleles.to.pgs.dosage` to recognize `*` as a non-risk allele.
- Small bug fixes discovered during testing in `apply.polygenic.score` and `create.pgs.with.continuous.phenotype`
- Added new test cases where needed.

- [x] I have read the [code review guidelines](https://uclahs-cds.atlassian.net/wiki/spaces/BOUTROSLAB/pages/3187646/Code+Review+Guidelines) and the [code review best practice on GitHub check-list](https://uclahs-cds.atlassian.net/wiki/spaces/BOUTROSLAB/pages/3189956/Code+Review+Best+Practice+on+GitHub+-+Check+List).

- [x] The name of the branch is meaningful and well formatted following the [standards](https://uclahs-cds.atlassian.net/wiki/spaces/BOUTROSLAB/pages/3189956/Code+Review+Best+Practice+on+GitHub+-+Check+List), using \[AD_username (or 5 letters of AD if AD is too long)-\[brief_description_of_branch].

- [x] I have set up or verified the branch protection rule following the [github standards](https://uclahs-cds.atlassian.net/wiki/spaces/BOUTROSLAB/pages/3190380/GitHub+Standards#GitHubStandards-Branchprotectionrule) before opening this pull request.

- [x] I have added the changes included in this pull request to `NEWS` under the next release version or unreleased, and updated the date.

- [ ] I have updated the version number in `metadata.yaml` and `DESCRIPTION`.

- [x] Both `R CMD build` and `R CMD check` run successfully.

Closes #61 

## Testing Results

All tests PASS

### CODE REVIEW

File: DESCRIPTION [hunk 1]
```diff
@@ -29,5 +29,5 @@ Config/testthat/edition: 3
 License: GPL-2
 Encoding: UTF-8
 LazyData: true
-RoxygenNote: 7.3.1
+RoxygenNote: 7.3.2
```
Comment (dan-knight) [inline DESCRIPTION:32]: Any particular reason why this incremented?

File: R/apply-pgs.R [hunk 2]
```diff
@@ -345,7 +345,12 @@ apply.polygenic.score <- function(
     sample.coordinate.to.row.dict.hash <- new.env(hash = TRUE, parent = emptyenv());
 
     for (i in 1:nrow(merged.vcf.with.pgs.data)) {
+        # skip if the variant is missing from all samples
+        if (is.na(merged.vcf.with.pgs.data[i, 'Indiv'])) {
+            next;
```
Comment (dan-knight) [inline R/apply-pgs.R:350]: Might be good to include a message about the skipped variant.

**Review by dan-knight — APPROVED** [review]
Code looks good to me!

File: DESCRIPTION (hunk 1 above)
Comment (alkaZeltser) [reply DESCRIPTION:32]: It was done automatically by `devtools::document()`, possibly I updated Roxygen since the last time, not sure though.

File: R/apply-pgs.R (hunk 2 above)
Comment (alkaZeltser) [reply R/apply-pgs.R:350]: This is deep in the multiallelic site handling algorithm, it's not useful to the user. Missing sites are reported in the final output.

**Comment by alkaZeltser** [comment]
> Code looks good to me! Just make sure to update the date/version and add the functional changes to the changelog.

Should I do that with this PR or wait until the release PR?

**Review by forbiddenpersimmon — APPROVED** [review]
LGTM!

**Comment by dan-knight** [comment]
> Should I do that with this PR or wait until the release PR?

I usually just keep it up to date as I go along, but the other PR is up already so I'm fine with just handling it there.

**Comment by alkaZeltser** [comment]
> > Should I do that with this PR or wait until the release PR?
> 
> I usually just keep it up to date as I go along, but the other PR is up already so I'm fine with just handling it there.

I guess what I'm confused about is I already did update NEWS/changelog with my changes under "unreleased" but it sounds like you want me to also increment the version even when I am not ready to make another release. I didn't think the version should be incremented after every PR?

**Comment by dan-knight** [comment]
> I guess what I'm confused about is I already did update NEWS/changelog with my changes under "unreleased" but it sounds like you want me to also increment the version even when I am not ready to make another release.

Ah, sorry for the confusion. You did it right, I just didn't see the NEWS.md changes in this PR. All good!

**Review by RoniHaas — APPROVED** [review]
I agree about how you handled the * as a non-risk allele!

A small unrelated suggestion is to consider testing strand flip.

**Comment by alkaZeltser** [comment]
> I agree about how you handled the * as a non-risk allele!
> 
> A small unrelated suggestion is to consider testing strand flip.

Good point, I've started an issue for potential new feature in the future.
